[tools]
poetry = 'latest'
python = '3.12'

[tasks.default]
run = 'python -m src'

[env]
# the Telegram bot token https://telegram.me/BotFather
BOT_TOKEN = '0000000000:aaaaaaaaaaaaaaaaaaaa'
# to connect to MTProto, which we use to upload media files (retrieve from https://my.telegram.org)
API_ID = '0000000'
API_HASH = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
# the Telegram account IDs that will have administrator permissions of the bot
BOT_ADMINS = '000000,000000,000000'
#TELEGRAM_LOG_CHAT_ID = '-10000000000'
DEBUG = 1

# PLUGINGS
HADITH_SEARCH_ENDPOINT = ''
EXCHANGE_RATE_API_KEY = ''

[env.mise]
file = '.env'
